/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-surface-variant": "#54433a",
        "primary-fixed-dim": "#ffb783",
        "on-primary-fixed": "#301400",
        "inverse-on-surface": "#f2f1ee",
        "on-surface": "#1a1c1a",
        "tertiary-fixed-dim": "#ffb68d",
        "on-secondary-container": "#396b69",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e3e2e0",
        "on-tertiary-container": "#ffc2a0",
        "tertiary-fixed": "#ffdbc9",
        "surface": "#faf9f6",
        "error": "#ba1a1a",
        "surface-variant": "#e3e2e0",
        "secondary-fixed-dim": "#9dd0cd",
        "tertiary-container": "#914100",
        "on-secondary-fixed-variant": "#1a4e4c",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf9f6",
        "secondary-container": "#b6e9e6",
        "background": "#faf9f6",
        "outline-variant": "#dac2b6",
        "inverse-surface": "#2f312f",
        "inverse-primary": "#ffb783",
        "surface-container": "#efeeeb",
        "on-tertiary-fixed": "#321200",
        "secondary": "#356664",
        "outline": "#877369",
        "surface-container-low": "#f4f3f1",
        "on-error": "#ffffff",
        "primary": "#683200",
        "on-background": "#1a1c1a",
        "on-primary-fixed-variant": "#713700",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#00201f",
        "surface-tint": "#944a00",
        "on-tertiary-fixed-variant": "#763400",
        "secondary-fixed": "#b9ece9",
        "surface-container-high": "#e9e8e5",
        "surface-dim": "#dbdad7",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffdcc5",
        "primary-container": "#8b4500",
        "on-error-container": "#93000a",
        "on-primary-container": "#ffc299",
        "tertiary": "#6d2f00"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Manrope"],
        "label": ["Manrope"],
        "plus-jakarta": ["Plus Jakarta Sans", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
